
export const LOADER_STARTED = "LOADER_STARTED";
export const SET_LOADING_TRUE = "SET_LOADING_TRUE";
export const SAVE_USER_SUCCESS = 'SAVE_USER_SUCCESS';
export const SAVE_USER_FAILED = 'SAVE_USER_FAILED';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';
export const FETCH_USER_SUCCESS ="FETCH_USER_SUCCESS";
export const LOGIN_USER_SUCCESS ="LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILED ="LOGIN_USER_FAILED";
export const FETCH_CODES_FAILED ="FETCH_CODES_FAILED";
export const FETCH_CODES_SUCCESS ="FETCH_CODES_SUCCESS";